// IntelliJ plugin for SFL, built for IntelliJ IDEA Community 2024.2+.
//
// The LSP client is LSP4IJ (Red Hat), which works on Community — the official
// com.intellij.platform.lsp API is paid-IDE only, and re-implementing PSI by hand
// would mean a second grammar to keep in sync. Highlighting here comes from a
// small hand lexer whose keyword and builtin tables are generated by
// tools/gen-editor-syntax.sfl, so they cannot drift from the compiler.

plugins {
    id("java")
    id("org.jetbrains.intellij.platform") version "2.18.1"
}

group = "com.fartech"
version = "0.3.2"

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity("2024.2.4")
        plugins("com.redhat.devtools.lsp4ij:0.19.3")
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

intellijPlatform {
    pluginConfiguration {
        ideaVersion {
            sinceBuild = "242"
        }
    }
    buildSearchableOptions = false
}
