#!/usr/bin/env bash
#
# Assembles docs/SFL-使用手册.md from the prose template plus a builtin reference
# generated by the interpreter itself, so the reference can never go stale.
set -euo pipefail
cd "$(dirname "$0")/.."

SFL=${SFL:-target/scala-3.8.4/sfl}
TEMPLATE=docs/manual-template.md
OUTPUT=docs/SFL-使用手册.md
MARKER='<!-- BUILTIN-REFERENCE -->'

if [[ ! -x "$SFL" ]]; then
  echo "no binary at $SFL — run: sbt nativeLink" >&2
  exit 1
fi

reference=$(mktemp)
trap 'rm -f "$reference"' EXIT
"$SFL" tools/gen-builtin-reference.sfl > "$reference"

if ! grep -qF "$MARKER" "$TEMPLATE"; then
  echo "$TEMPLATE is missing the $MARKER placeholder" >&2
  exit 1
fi

# Keep the stated total in sync with what was actually generated.
count=$(grep -c '^| `' "$reference")
awk -v marker="$MARKER" -v ref="$reference" -v count="$count" '
  index($0, marker) {
    while ((getline line < ref) > 0) print line
    close(ref)
    next
  }
  { gsub(/共 [0-9]+ 个内置函数/, "共 " count " 个内置函数"); print }
' "$TEMPLATE" > "$OUTPUT"

# Every chapter the table of contents promises must actually be in the output. An
# earlier edit silently dropped a whole chapter; this makes that a build failure.
missing=""
for n in $(grep -oE '^[0-9]+\. \[' "$TEMPLATE" | grep -oE '^[0-9]+'); do
  grep -qE "^## $n\. " "$OUTPUT" || missing="$missing $n"
done
if [[ -n "$missing" ]]; then
  echo "$OUTPUT is missing chapter(s):$missing" >&2
  exit 1
fi

echo "wrote $OUTPUT ($count builtins documented)"
